import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Time from "./components/time";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex items-center justify-between p-2 text-white bg-gray-700">
          <div>
            <Link href={"/"} className="p-2 mr-4 text-2xl font-extrabold">
              DevIngsu
            </Link>
            <Link href={"/list"} className="p-2 mr-4 text-2xl font-extrabold">
              리스트
            </Link>
          </div>
          <Time className="mr-5 " />
        </nav>
        {children}
      </body>
    </html>
  );
}
